
# .github/FUNDING.yml
# Add GitHub Sponsors username if you set that up:
# github: [ your-username ]

custom:
  - https://cash.app/$nautidogsailing
#  - https://paypal.me/YourPayPalLink   # replace with your actual PayPal link if you want
