name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path requirements.txt) { python -m pip install -r requirements.txt } else { python -m pip install numpy }

    - name: Run unit tests
      run: |
        python -m pytest -q

    - name: Quick smoke: run recursive real-file finder (no parsing)
      run: |
        python -c "import test_real_files_recursive as t; print('Found', len(t.find_sonar_files('.')) )"
